FROM mambaorg/micromamba:1.3.1
LABEL AUTHOR=earlm@lanl.gov
 
ARG SSL_KEYSTORE_PASSWORD
USER root
RUN apt-get -y update \
    && apt-get install -y git \
    && apt-get install -y python3 \
    && apt-get install -y wget zip bc \
    && apt-get clean
RUN micromamba install --yes --name base --channel bioconda --channel conda-forge \
    prodigal orthofinder=2.5.4 bbmap=39.01 fasttree hmmer pal2nal prodigal ete3 raxml trimal parallel r-essentials \
    && micromamba clean --all --yes \
    && eval "$(micromamba shell hook --shell=bash)" \
    && micromamba activate \
    && Path_to_gits=/opt/Path_to_gits \
    && echo "Path_to_gits=/opt/Path_to_gits" >> /etc/environment \
    && mkdir $Path_to_gits \
    && cd $Path_to_gits/ \
    && git clone https://github.com/smirarab/ASTRAL.git \
    && cd ASTRAL \
    && unzip Astral.5.7.8.zip \
    && cd $Path_to_gits/ \
    && git clone https://github.com/nylander/catfasta2phyml.git \
    && git clone https://github.com/dportik/Alignment_Assessment.git \
    && cd Alignment_Assessment/ \
    && 2to3 -w Alignment_Assessment_v2.py \
    && cd /opt \
    && wget https://github.com/ParBLiSS/FastANI/releases/download/v1.33/fastANI-Linux64-v1.33.zip \
    && unzip fastANI-Linux64-v1.33.zip \
    && mkdir /opt/apps/ \
    && mv fastANI /opt/apps/ \
    && chmod a+rwx /opt/apps/* \
    && rm fastANI-Linux64-v1.33.zip \
    && cd $Path_to_gits \
    && git clone https://github.com/eamiddlebrook/OrthoPhyl.git \
    && cd OrthoPhyl \
    && chmod a+rw OrthoPhyl.sh


RUN mkdir /working_dir && chmod 777 /working_dir

SHELL ["/bin/bash", "-c"]
ENV PATH="/opt/Path_to_gits/OrthoPhyl/:/opt/miniconda3/bin/:$PATH"
ENV Path_to_gits="/opt/Path_to_gits"
ENV OrthoPhyl="bash /opt/Path_to_gits/OrthoPhyl/OrthoPhyl.sh"
ENV FASTANI="/opts/apps/fastANI"
ENV ASTRAL_cmd="$Path_to_gits/ASTRAL/Astral/astral.5.7.8.jar"
ENV catfasta2phyml_cmd="$Path_to_gits/catfasta2phyml/catfasta2phyml.pl"
ENV Alignment_Assessment="$Path_to_gits/Alignment_Assessment/Alignment_Assessment_v2.py"
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV NOW="$(date)"


ENTRYPOINT ["OrthoPhyl.sh"]
